version: '{branch}-{build}'

clone_depth: 5

platform:
  - x64

environment:
  ARTIFACTS_DIR_NAME: KlayGE_Samples
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PROJECT: vs2019
      COMPILER: vc142
      BUILD_DIR: vc142
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PROJECT: ninja
      COMPILER: mingw
      BUILD_DIR: mingw
      MINGW_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

configuration:
  - Release

artifacts:
  - path: Build/$(BUILD_DIR)/$(ARTIFACTS_DIR_NAME)
    name: $(ARTIFACTS_DIR_NAME)_$(COMPILER)_$(PLATFORM)_$(CONFIGURATION)

cache:
  - Build/%BUILD_DIR%/External
  - Build/%BUILD_DIR%/Ninja
  - External
  - KlayGE/media
  - KlayGE/Samples/media
  - KlayGE/Tests/media
  - KlayGE/Tools/media
  - KlayGE/Tutorials/media

install:
  - if "%PROJECT%" equ "ninja" choco install ninja

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - if "%COMPILER%" equ "mingw" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%COMPILER%" equ "mingw" set PATH=%MINGW_PATH%;%PATH%
  # Restore ninja files
  - if "%PROJECT%" equ "ninja" (
      if EXIST Build\%BUILD_DIR%\Ninja (
        if EXIST Build\%BUILD_DIR%\Ninja\.ninja_deps (
          move /Y Build\%BUILD_DIR%\Ninja\.ninja_* Build\%BUILD_DIR%\
        )
      )
    )
  - if EXIST Build\%BUILD_DIR%\Ninja rd /S /Q Build\%BUILD_DIR%\Ninja
  # Reset the repo to restore changes in External
  - git reset --hard

build_script:
  - git config --global user.email "dummy@example.com"
  - git config --global user.name "Dummy Name"
  - python Build.py %PROJECT% %COMPILER% %PLATFORM% %CONFIGURATION%

after_build:
  # Generate artifacts
  - python Package.py Build/%BUILD_DIR%/%ARTIFACTS_DIR_NAME% %PROJECT% %COMPILER% %PLATFORM% %CONFIGURATION%
  - echo %APPVEYOR_REPO_COMMIT% > Build/%BUILD_DIR%/%ARTIFACTS_DIR_NAME%/GIT-COMMIT.txt

on_success:
  # Backup ninja files to a folder
  - mkdir Build\%BUILD_DIR%\Ninja
  - if "%PROJECT%" equ "ninja" move /Y Build\%BUILD_DIR%\.ninja_* Build\%BUILD_DIR%\Ninja
